## Pandas learning

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('data\Fortune 500 Companies.csv')

In [4]:
df.head()

,name,rank,year,industry,sector,headquarters_state,headquarters_city,market_value_mil,revenue_mil,profit_mil,asset_mil,employees,founder_is_ceo,female_ceo,newcomer_to_fortune_500,global_500
0,General Motors Corporation,1,1996,Motor Vehicles & Parts,NaN,MI,NaN,NaN,168828.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ford Motor Company,2,1996,Motor Vehicles & Parts,NaN,MI,NaN,NaN,137137.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Exxon Corporation,3,1996,Petroleum Refining,NaN,TX,NaN,NaN,110009.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Wal-Mart Stores, Inc.",4,1996,General Merchandisers,NaN,AR,NaN,NaN,93627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AT&T Corp.,5,1996,Telecommunications,NaN,NY,NaN,NaN,79609.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
a=df.groupby(['sector'])
len(a)

21

In [23]:
a.head()

,name,rank,year,industry,sector,headquarters_state,headquarters_city,market_value_mil,revenue_mil,profit_mil,asset_mil,employees,founder_is_ceo,female_ceo,newcomer_to_fortune_500,global_500
9440,Walmart,1,2015,General Merchandisers,Retailing,AR,Bentonville,265344.0,485651.0,16363.0,203706.0,2200000.0,no,no,no,NaN
9441,Exxon Mobil,2,2015,Petroleum Refining,Energy,TX,Irving,356549.0,382597.0,32520.0,349493.0,83700.0,no,no,no,NaN
9442,Chevron,3,2015,Petroleum Refining,Energy,CA,San Ramon,197381.0,203784.0,19241.0,266026.0,64700.0,no,no,no,NaN
9443,Berkshire Hathaway,4,2015,Insurance: Property and Casualty (Stock),Financials,NE,Omaha,357344.0,194673.0,19872.0,526186.0,316000.0,no,no,no,NaN
9444,Apple,5,2015,"Computers, Office Equipment",Technology,CA,Cupertino,724773.0,182795.0,39510.0,231839.0,97200.0,no,no,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9782,AECOM,343,2015,Engineering & Construction,Engineering & Construction,CA,Los Angeles,4792.0,8357.0,230.0,6123.0,43300.0,no,no,no,NaN
9790,PVH,351,2015,Apparel,Apparel,NY,New York,8794.0,8241.0,439.0,10932.0,25850.0,no,no,no,NaN
9793,D.R. Horton,354,2015,Homebuilders,Engineering & Construction,TX,Fort Worth,10407.0,8025.0,534.0,10203.0,5621.0,no,no,no,NaN
9813,Ralph Lauren,374,2015,Apparel,Apparel,NY,New York,11482.0,7450.0,776.0,6090.0,18500.0,no,no,no,NaN
9929,Hanesbrands,490,2015,Apparel,Apparel,NC,Winston-Salem,13431.0,5325.0,405.0,5222.0,59500.0,no,no,yes,NaN

In [22]:
a.size()

sector
Aerospace & Defense               96
Apparel                           47
Business Services                169
Chemicals                        125
Energy                           547
Engineering & Construction       112
Financials                       777
Food & Drug Stores                55
Food, Beverages & Tobacco        223
Health Care                      368
Hotels, Restaurants & Leisure     89
Household Products               103
Industrials                      155
Materials                        177
Media                             93
Motor Vehicles & Parts           100
Retailing                        422
Technology                       393
Telecommunications                81
Transportation                   158
Wholesalers                      210
dtype: int64

In [17]:
q=df['name'].unique()
q.shape

(2255,)

In [10]:
df['name'].value_counts()

name
U.S. Bancorp               28
Edison International       28
Johnson & Johnson          28
Abbott Laboratories        28
Owens Corning              26
                           ..
Par Pacific Holdings        1
RPM International           1
Select Medical Holdings     1
MDU Resources Group         1
Electronic Arts             1
Name: count, Length: 2255, dtype: int64

In [5]:
df.isnull().sum()

name                          0
rank                          0
year                          0
industry                      0
sector                     9440
headquarters_state            0
headquarters_city          6445
market_value_mil           8755
revenue_mil                   0
profit_mil                 8443
asset_mil                  8440
employees                  9440
founder_is_ceo             9440
female_ceo                 9440
newcomer_to_fortune_500    9440
global_500                 9940
dtype: int64

In [6]:
df.shape

(13940, 16)

In [11]:
len(df)

13940