## Pandas learning

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('data\Fortune 500 Companies.csv')

In [5]:
df.head()

,name,rank,year,industry,sector,headquarters_state,headquarters_city,market_value_mil,revenue_mil,profit_mil,asset_mil,employees,founder_is_ceo,female_ceo,newcomer_to_fortune_500,global_500
0,General Motors Corporation,1,1996,Motor Vehicles & Parts,NaN,MI,NaN,NaN,168828.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ford Motor Company,2,1996,Motor Vehicles & Parts,NaN,MI,NaN,NaN,137137.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Exxon Corporation,3,1996,Petroleum Refining,NaN,TX,NaN,NaN,110009.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Wal-Mart Stores, Inc.",4,1996,General Merchandisers,NaN,AR,NaN,NaN,93627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AT&T Corp.,5,1996,Telecommunications,NaN,NY,NaN,NaN,79609.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
a=df.groupby(['sector'])
len(a)

21

In [7]:
a.head()

,name,rank,year,industry,sector,headquarters_state,headquarters_city,market_value_mil,revenue_mil,profit_mil,asset_mil,employees,founder_is_ceo,female_ceo,newcomer_to_fortune_500,global_500
9440,Walmart,1,2015,General Merchandisers,Retailing,AR,Bentonville,265344.0,485651.0,16363.0,203706.0,2200000.0,no,no,no,NaN
9441,Exxon Mobil,2,2015,Petroleum Refining,Energy,TX,Irving,356549.0,382597.0,32520.0,349493.0,83700.0,no,no,no,NaN
9442,Chevron,3,2015,Petroleum Refining,Energy,CA,San Ramon,197381.0,203784.0,19241.0,266026.0,64700.0,no,no,no,NaN
9443,Berkshire Hathaway,4,2015,Insurance: Property and Casualty (Stock),Financials,NE,Omaha,357344.0,194673.0,19872.0,526186.0,316000.0,no,no,no,NaN
9444,Apple,5,2015,"Computers, Office Equipment",Technology,CA,Cupertino,724773.0,182795.0,39510.0,231839.0,97200.0,no,no,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9782,AECOM,343,2015,Engineering & Construction,Engineering & Construction,CA,Los Angeles,4792.0,8357.0,230.0,6123.0,43300.0,no,no,no,NaN
9790,PVH,351,2015,Apparel,Apparel,NY,New York,8794.0,8241.0,439.0,10932.0,25850.0,no,no,no,NaN
9793,D.R. Horton,354,2015,Homebuilders,Engineering & Construction,TX,Fort Worth,10407.0,8025.0,534.0,10203.0,5621.0,no,no,no,NaN
9813,Ralph Lauren,374,2015,Apparel,Apparel,NY,New York,11482.0,7450.0,776.0,6090.0,18500.0,no,no,no,NaN
9929,Hanesbrands,490,2015,Apparel,Apparel,NC,Winston-Salem,13431.0,5325.0,405.0,5222.0,59500.0,no,no,yes,NaN

In [8]:
a.groups

{'Aerospace & Defense': [9466, 9484, 9503, 9539, 9563, 9568, 9658, 9691, 9741, 9829, 9835, 9963, 9984, 9999, 10027, 10057, 10059, 10148, 10184, 10221, 10317, 10328, 10429, 10463, 10489, 10495, 10529, 10553, 10555, 10639, 10667, 10712, 10819, 10832, 10931, 10966, 10990, 10998, 11038, 11057, 11058, 11147, 11164, 11215, 11320, 11344, 11346, 11354, 11467, 11485, 11499, 11531, 11547, 11553, 11666, 11668, 11729, 11789, 11810, 11859, 11913, 11978, 11979, 11996, 12022, 12035, 12047, 12165, 12175, 12189, 12296, 12345, 12488, 12493, 12496, 12523, 12525, 12602, 12704, 12766, 12994, 12997, 12999, 13033, 13040, 13145, 13241, 13309, 13496, 13497, 13499, 13544, 13552, 13685, 13757, 13814], 'Apparel': [9545, 9687, 9790, 9813, 9929, 10030, 10170, 10279, 10293, 10387, 10527, 10669, 10774, 10810, 10871, 11028, 11181, 11271, 11360, 11372, 11529, 11691, 11763, 11883, 11912, 11923, 11939, 12024, 12172, 12262, 12375, 12408, 12424, 12434, 12524, 12702, 12843, 12871, 12889, 13022, 13319, 13324, 13397, 13532, 13788, 13861, 13927], 'Business Services': [9583, 9639, 9646, 9656, 9677, 9690, 9704, 9747, 9762, 9811, 9861, 9900, 9907, 9910, 9933, 9939, 10083, 10125, 10138, 10143, 10160, 10187, 10188, 10233, 10246, 10251, 10294, 10331, 10343, 10379, 10406, 10407, 10420, 10424, 10431, 10585, 10618, 10626, 10631, 10640, 10679, 10681, 10703, 10706, 10738, 10740, 10784, 10817, 10891, 10898, 10910, 10917, 10929, 10932, 10939, 11082, 11100, 11127, 11139, 11141, 11161, 11175, 11182, 11193, 11235, 11265, 11298, 11304, 11363, 11402, 11405, 11426, 11433, 11437, 11439, 11580, 11592, 11637, 11643, 11645, 11650, 11652, 11678, 11753, 11761, 11771, 11800, 11818, 11829, 11898, 11902, 11909, 11927, 11929, 11937, 12076, 12097, 12121, 12130, 12139, ...], 'Chemicals': [9487, 9526, 9636, 9637, 9652, 9688, 9698, 9705, 9723, 9744, 9759, 9810, 9834, 9866, 9995, 10040, 10121, 10128, 10145, 10192, 10201, 10216, 10227, 10235, 10255, 10393, 10412, 10501, 10552, 10622, 10643, 10650, 10675, 10714, 10728, 10733, 10748, 10816, 10906, 10921, 10923, 10986, 11129, 11130, 11138, 11154, 11203, 11221, 11249, 11284, 11291, 11321, 11387, 11390, 11394, 11474, 11616, 11644, 11654, 11715, 11752, 11764, 11783, 11791, 11865, 11873, 11893, 12017, 12042, 12091, 12119, 12148, 12152, 12282, 12294, 12295, 12321, 12330, 12409, 12420, 12521, 12535, 12583, 12601, 12659, 12676, 12779, 12785, 12794, 12827, 12899, 12911, 12916, 12928, 13003, 13041, 13114, 13152, 13157, 13232, ...], 'Energy': [9441, 9442, 9446, 9452, 9464, 9490, 9492, 9498, 9506, 9516, 9535, 9550, 9554, 9555, 9558, 9566, 9576, 9580, 9581, 9588, 9589, 9591, 9594, 9601, 9602, 9606, 9617, 9621, 9622, 9623, 9632, 9635, 9643, 9645, 9657, 9665, 9666, 9675, 9676, 9680, 9682, 9685, 9694, 9696, 9709, 9713, 9714, 9752, 9768, 9784, 9788, 9789, 9792, 9796, 9806, 9809, 9818, 9822, 9837, 9843, 9845, 9857, 9877, 9885, 9887, 9888, 9896, 9904, 9935, 9941, 9953, 9969, 9971, 9981, 10004, 10029, 10034, 10037, 10043, 10054, 10056, 10060, 10101, 10102, 10104, 10105, 10114, 10117, 10127, 10129, 10131, 10132, 10137, 10153, 10155, 10156, 10162, 10164, 10168, 10182, ...], 'Engineering & Construction': [9575, 9678, 9725, 9782, 9793, 9800, 9803, 9860, 9863, 9892, 9919, 10094, 10095, 10174, 10199, 10240, 10253, 10291, 10320, 10372, 10417, 10437, 10588, 10600, 10671, 10698, 10699, 10763, 10792, 10794, 10799, 10854, 10885, 10933, 10936, 11092, 11103, 11150, 11169, 11236, 11255, 11278, 11280, 11307, 11367, 11383, 11419, 11593, 11596, 11603, 11633, 11647, 11722, 11751, 11779, 11814, 11863, 11867, 11875, 12086, 12102, 12120, 12122, 12145, 12200, 12246, 12248, 12283, 12356, 12365, 12369, 12568, 12587, 12628, 12635, 12664, 12682, 12717, 12723, 12783, 12822, 12850, 12880, 12891, 12909, 13063, 13070, 13198, 13199, 13201, 13206, 13224, 13252, 13296, 13328, 13336, 13368, 13392, 13399, 13558, ...], 'Financials': [9443, 9447, 9456, 9460, 9462, 9467, 9469, 9478, 9480, 9481, 9485, 9494, 9515, 9517, 9519, 9521, 9524, 9527, 9528, 9531, 9532, 9533, 9548, 9551, 9561, 9565, 9571, 9577, 9592, 9599, 9628, 9631, 9650, 9654, 9662, 9674, 9686, 9693, 9703, 9706, 9707, 9712, 9717, 9718, 9721, 9724, 9731, 9734, 9742, 9743, 9753, 9760, 9766, 9772, 9774, 9795, 9797, 9812, 9824, 9826, 9830, 9855, 9864, 9865, 9874, 9875, 9898, 9902, 9911, 9917, 9918, 9920, 9924, 9927, 9938, 9943, 9955, 9962, 9965, 9966, 9968, 9974, 9979, 9982, 9988, 9989, 10000, 10008, 10012, 10013, 10015, 10017, 10020, 10021, 10022, 10024, 10039, 10044, 10051, 10053, ...], 'Food & Drug Stores': [9449, 9459, 9474, 9523, 9540, 9556, 9603, 9653, 9946, 9956, 9958, 10026, 10046, 10099, 10120, 10456, 10457, 10488, 10524, 10530, 10597, 10615, 10956, 10958, 10992, 11027, 11033, 11119, 11456, 11459, 11491, 11530, 11546, 11640, 11958, 11962, 11994, 12026, 12089, 12455, 12456, 12491, 12508, 12571, 12876, 12957, 12960, 12991, 13015, 13087, 13463, 13466, 13492, 13517, 13600], 'Food, Beverages & Tobacco': [9473, 9483, 9502, 9508, 9522, 9530, 9541, 9604, 9608, 9610, 9612, 9642, 9649, 9683, 9711, 9745, 9749, 9776, 9781, 9807, 9815, 9856, 9876, 9901, 9906, 9980, 9983, 10001, 10005, 10023, 10033, 10045, 10088, 10092, 10100, 10115, 10146, 10154, 10181, 10205, 10243, 10275, 10276, 10301, 10336, 10352, 10368, 10391, 10395, 10399, 10483, 10484, 10503, 10521, 10532, 10543, 10545, 10548, 10587, 10604, 10636, 10648, 10655, 10662, 10734, 10778, 10785, 10790, 10808, 10847, 10855, 10866, 10895, 10925, 10984, 10987, 11019, 11026, 11035, 11047, 11053, 11056, 11093, 11121, 11155, 11165, 11214, 11260, 11262, 11297, 11301, 11318, 11322, 11325, 11357, 11385, 11417, 11420, 11487, 11488, ...], 'Health Care': [9453, 9461, 9476, 9477, 9488, 9495, 9497, 9510, 9514, 9529, 9557, 9573, 9574, 9584, 9585, 9590, 9609, 9624, 9625, 9634, 9655, 9670, 9673, 9737, 9739, 9740, 9763, 9777, 9808, 9814, 9817, 9819, 9853, 9879, 9905, 9915, 9930, 9934, 9944, 9945, 9951, 9960, 9961, 9972, 9978, 9985, 9991, 9994, 10002, 10011, 10018, 10025, 10062, 10063, 10064, 10069, 10077, 10079, 10080, 10107, 10111, 10139, 10140, 10141, 10202, 10207, 10217, 10225, 10226, 10229, 10230, 10244, 10264, 10297, 10298, 10311, 10359, 10369, 10370, 10386, 10396, 10404, 10408, 10445, 10446, 10461, 10468, 10474, 10482, 10492, 10493, 10502, 10505, 10508, 10509, 10531, 10550, 10562, 10569, 10571, ...], 'Hotels, Restaurants & Leisure': [9549, 9626, 9648, 9660, 9667, 9719, 9728, 9764, 9767, 9881, 9916, 9936, 10048, 10085, 10134, 10157, 10180, 10193, 10248, 10310, 10383, 10405, 10551, 10570, 10602, 10680, 10688, 10736, 10824, 10838, 10861, 10900, 11066, 11070, 11071, 11166, 11219, 11263, 11335, 11336, 11386, 11411, 11418, 11560, 11588, 11590, 11669, 11705, 11784, 11801, 11804, 11815, 11887, 11933, 12053, 12095, 12096, 12174, 12188, 12277, 12300, 12302, 12311, 12393, 12564, 12596, 12732, 12802, 12816, 12903, 12917, 13059, 13091, 13209, 13274, 13298, 13303, 13389, 13404, 13429, 13564, 13608, 13631, 13754, 13793, 13841, 13844, 13870, 13877], 'Household Products': [9471, 9537, 9579, 9618, 9700, 9710, 9761, 9773, 9787, 9801, 9878, 9886, 9894, 9908, 9973, 10090, 10113, 10195, 10200, 10267, 10277, 10284, 10309, 10373, 10380, 10389, 10394, 10475, 10594, 10621, 10647, 10689, 10692, 10750, 10811, 10857, 10883, 10892, 10913, 10981, 11102, 11123, 11135, 11167, 11197, 11254, 11310, 11312, 11361, 11407, 11424, 11484, 11610, 11641, 11667, 11670, 11682, 11754, 11773, 11805, 11916, 11989, 12114, 12142, 12154, 12159, 12255, 12260, 12305, 12323, 12413, 12433, 12482, 12597, 12627, 12648, 12652, 12760, 12764, 12837, 12865, 12866, 12895, 12933, 12986, 13121, 13150, 13151, 13167, 13269, 13287, 13352, 13383, 13398, 13435, 13490, 13638, 13666, 13667, 13670, ...], 'Industrials': [9493, 9513, 9525, 9559, 9587, 9593, 9640, 9669, 9735, 9785, 9816, 9848, 9882, 9925, 9950, 9998, 10014, 10032, 10036, 10067, 10073, 10087, 10150, 10163, 10299, 10316, 10335, 10351, 10358, 10452, 10512, 10513, 10533, 10544, 10576, 10578, 10598, 10603, 10641, 10690, 10737, 10776, 10809, 10825, 10831, 10864, 10881, 10884, 10957, 11004, 11016, 11036, 11041, 11079, 11088, 11094, 11117, 11143, 11195, 11232, 11281, 11286, 11299, 11353, 11359, 11384, 11460, 11497, 11516, 11526, 11534, 11567, 11569, 11587, 11617, 11653, 11657, 11718, 11747, 11774, 11834, 11851, 11861, 11891, 11972, 12001, 12023, 12031, 12057, 12071, 12101, 12115, 12163, 12168, 12216, 12223, 12289, 12316, 12327, 12361, ...], 'Materials': [9553, 9564, 9578, 9615, 9722, 9732, 9757, 9765, 9771, 9794, 9805, 9827, 9838, 9854, 9883, 9890, 9903, 9909, 9937, 10065, 10066, 10109, 10183, 10190, 10242, 10260, 10280, 10295, 10312, 10314, 10322, 10356, 10357, 10365, 10374, 10385, 10419, 10428, 10572, 10608, 10629, 10718, 10739, 10745, 10759, 10772, 10780, 10786, 10834, 10836, 10840, 10852, 10860, 10869, 10880, 10889, 10897, 11063, 11090, 11133, 11185, 11201, 11216, 11244, 11251, 11277, 11333, 11338, 11339, 11343, 11349, 11366, 11375, 11381, 11395, 11400, 11559, 11572, 11629, 11661, 11675, 11703, 11710, 11714, 11723, 11828, 11833, 11840, 11845, 11864, 11870, 11871, 11877, 11882, 11919, 12078, 12083, 12116, 12186, 12211, ...], 'Media': [9496, 9536, 9543, 9651, 9661, 9697, 9770, 9831, 9868, 9869, 9880, 9992, 10035, 10038, 10142, 10152, 10194, 10266, 10305, 10345, 10353, 10491, 10534, 10540, 10632, 10663, 10769, 10771, 10827, 10851, 10865, 10930, 10994, 11037, 11048, 11136, 11160, 11229, 11289, 11316, 11345, 11348, 11391, 11492, 11543, 11636, 11656, 11687, 11731, 11739, 11780, 11819, 11844, 11884, 11905, 11988, 12050, 12103, 12214, 12219, 12226, 12245, 12257, 12402, 12410, 12489, 12548, 12554, 12686, 12729, 12765, 12776, 12812, 12904, 12924, 12938, 12992, 13054, 13055, 13226, 13249, 13265, 13313, 13335, 13487, 13557, 13568, 13573, 13687, 13739, 13779, 13820, 13923], 'Motor Vehicles & Parts': [9445, 9448, 9505, 9597, 9605, 9613, 9614, 9715, 9751, 9780, 9783, 9786, 9833, 9849, 9947, 9948, 10009, 10086, 10093, 10108, 10220, 10249, 10273, 10278, 10363, 10367, 10409, 10447, 10449, 10590, 10623, 10722, 10744, 10761, 10822, 10886, 10949, 10950, 11087, 11126, 11199, 11228, 11240, 11259, 11331, 11332, 11388, 11451, 11452, 11583, 11586, 11642, 11706, 11740, 11760, 11806, 11812, 11857, 11951, 11957, 12063, 12105, 12124, 12155, 12251, 12306, 12308, 12343, 12399, 12460, 12461, 12539, 12618, 12638, 12685, 12734, 12807, 12831, 12847, 12961, 12964, 13004, 13090, 13125, 13141, 13148, 13183, 13245, 13330, 13360, 13458, 13460, 13489, 13579, 13628, 13630, 13693, 13701, 13826, 13868], 'Retailing': [9440, 9457, 9472, 9475, 9489, 9511, 9538, 9542, 9544, 9572, 9595, 9596, 9598, 9616, 9627, 9633, 9641, 9663, 9671, 9684, 9689, 9699, 9701, 9708, 9716, 9720, 9730, 9733, 9746, 9750, 9754, 9769, 9775, 9804, 9820, 9821, 9823, 9825, 9832, 9839, 9841, 9862, 9889, 9899, 9913, 9921, 9940, 9954, 9967, 9977, 9986, 10010, 10028, 10042, 10050, 10071, 10075, 10078, 10082, 10084, 10116, 10119, 10130, 10135, 10136, 10167, 10173, 10176, 10177, 10179, 10197, 10206, 10208, 10219, 10232, 10236, 10238, 10241, 10269, 10281, 10285, 10300, 10304, 10313, 10318, 10319, 10332, 10354, 10366, 10378, 10434, 10439, 10440, 10455, 10462, 10477, 10479, 10511, 10526, 10549, ...], 'Technology': [9444, 9458, 9463, 9468, 9470, 9479, 9491, 9499, 9520, 9552, 9560, 9582, 9586, 9611, 9620, 9629, 9630, 9644, 9668, 9672, 9681, 9692, 9702, 9727, 9736, 9758, 9778, 9779, 9802, 9828, 9844, 9847, 9851, 9867, 9871, 9897, 9912, 9914, 9922, 9926, 9931, 9942, 9957, 9959, 9964, 9970, 9975, 9990, 9993, 10016, 10049, 10052, 10072, 10089, 10096, 10097, 10103, 10112, 10133, 10158, 10159, 10169, 10172, 10223, 10234, 10239, 10247, 10252, 10270, 10324, 10325, 10339, 10347, 10348, 10361, 10390, 10401, 10403, 10426, 10430, 10442, 10451, 10466, 10467, 10471, 10480, 10486, 10498, 10499, 10500, 10520, 10537, 10558, 10583, 10591, 10593, 10601, 10638, 10644, 10645, ...], 'Telecommunications': [9451, 9454, 9482, 9534, 9569, 9607, 9647, 9756, 9840, 9858, 9891, 9949, 9952, 9976, 10055, 10098, 10126, 10231, 10272, 10338, 10382, 10400, 10435, 10448, 10453, 10470, 10535, 10599, 10625, 10752, 10775, 10888, 10924, 10948, 10955, 10972, 11013, 11105, 11142, 11264, 11413, 11448, 11458, 11471, 11509, 11571, 11671, 11766, 11794, 11932, 11948, 11959, 11967, 12010, 12082, 12190, 12266, 12332, 12450, 12459, 12465, 12503, 12578, 12636, 12745, 12841, 12952, 12962, 12967, 13008, 13118, 13144, 13294, 13438, 13465, 13468, 13469, 13518, 13676, 13688, 13836], 'Transportation': [9486, 9504, 9509, 9512, 9518, 9562, 9600, 9664, 9679, 9695, 9846, 9852, 9870, 9872, 9873, 9893, 9895, 9923, 9987, 9997, 10006, 10007, 10019, 10068, 10081, 10147, 10178, 10209, 10292, 10329, 10334, 10344, 10346, 10355, 10371, 10398, 10485, 10497, 10506, 10510, 10522, 10577, 10582, 10630, 10651, 10696, 10723, 10833, 10842, 10846, 10868, 10874, 10877, 10983, 10989, 11010, 11014, 11020, 11080, 11081, 11125, 11132, 11204, 11223, 11294, 11326, 11334, 11341, 11347, 11427, 11435, 11480, 11486, 11507, 11508, 11517, 11573, 11581, 11619, 11624, 11699, 11716, 11793, 11802, 11807, 11813, 11838, 11915, 11931, 11982, 11986, 12007, 12009, 12015, 12080, 12088, 12135, 12147, 12206, 12222, ...], 'Wholesalers': [9450, 9455, 9465, 9500, 9501, 9507, 9546, 9547, 9567, 9570, 9619, 9638, 9659, 9726, 9729, 9738, 9748, 9755, 9791, 9798, 9799, 9836, 9842, 9850, 9859, 9884, 9928, 9932, 9996, 10003, 10031, 10041, 10047, 10058, 10061, 10106, 10122, 10124, 10151, 10215, 10224, 10254, 10256, 10259, 10262, 10274, 10290, 10296, 10308, 10330, 10362, 10402, 10413, 10416, 10423, 10444, 10450, 10454, 10496, 10546, 10547, 10557, 10563, 10610, 10619, 10637, 10682, 10686, 10721, 10727, 10743, 10764, 10770, 10773, 10777, 10789, 10798, 10803, 10812, 10859, 10905, 10912, 10926, 10928, 10945, 10951, 10953, 10993, 11022, 11052, 11060, 11067, 11108, 11110, 11116, 11177, 11186, 11226, 11239, 11257, ...]}

In [9]:
df.iloc[9466]

name                                    Boeing
rank                                        27
year                                      2015
industry                   Aerospace & Defense
sector                     Aerospace & Defense
headquarters_state                          IL
headquarters_city                      Chicago
market_value_mil                      105032.0
revenue_mil                            90762.0
profit_mil                              5446.0
asset_mil                              99198.0
employees                             165500.0
founder_is_ceo                              no
female_ceo                                  no
newcomer_to_fortune_500                     no
global_500                                 NaN
Name: 9466, dtype: object

In [11]:
a.get_group('Energy').shape[0]

C:\Users\BILAL.COM\AppData\Local\Temp\ipykernel_11456\200317036.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  a.get_group('Energy').shape[0]

547

In [12]:
a.get_group('Financials').shape[0]

C:\Users\BILAL.COM\AppData\Local\Temp\ipykernel_11456\3925339398.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  a.get_group('Financials').shape[0]

777

In [13]:
a.get_group('Technology').shape[0]

C:\Users\BILAL.COM\AppData\Local\Temp\ipykernel_11456\1028107296.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  a.get_group('Technology').shape[0]

393

In [15]:
a.first()

,name,rank,year,industry,headquarters_state,headquarters_city,market_value_mil,revenue_mil,profit_mil,asset_mil,employees,founder_is_ceo,female_ceo,newcomer_to_fortune_500,global_500
sector,,,,,,,,,,,,,,,
Aerospace & Defense,Boeing,27,2015,Aerospace & Defense,IL,Chicago,105032.0,90762.0,5446.0,99198.0,165500.0,no,no,no,yes
Apparel,Nike,106,2015,Apparel,OR,Beaverton,86679.0,27799.0,2693.0,18594.0,56500.0,no,no,no,yes
Business Services,ManpowerGroup,144,2015,Temporary Help,WI,Milwaukee,6746.0,20763.0,428.0,7183.0,26000.0,no,no,no,no
Chemicals,Dow Chemical,48,2015,Chemicals,MI,Midland,55546.0,58167.0,3772.0,68796.0,53216.0,no,no,no,yes
Energy,Exxon Mobil,2,2015,Petroleum Refining,TX,Irving,356549.0,382597.0,32520.0,349493.0,83700.0,no,no,no,yes
Engineering & Construction,Fluor,136,2015,Engineering & Construction,TX,Irving,8427.0,21532.0,511.0,8194.0,37508.0,no,no,no,no
Financials,Berkshire Hathaway,4,2015,Insurance: Property and Casualty (Stock),NE,Omaha,357344.0,194673.0,19872.0,526186.0,316000.0,no,no,no,yes
Food & Drug Stores,CVS Health,10,2015,Food & Drug Stores,RI,Woonsocket,117171.0,139367.0,4644.0,74252.0,177800.0,no,no,no,yes
"Food, Beverages & Tobacco",Archer Daniels Midland,34,2015,Food Production,IL,Chicago,29812.0,81201.0,2248.0,44027.0,33900.0,no,no,no,yes
Health Care,UnitedHealth Group,14,2015,Health Care: Insurance and Managed Care,MN,Minnetonka,112813.0,130474.0,5619.0,86382.0,170000.0,no,no,no,yes
"Hotels, Restaurants & Leisure",McDonald's,110,2015,Food Services,IL,Oak Brook,93651.0,27441.0,4758.0,34281.0,420000.0,no,no,no,yes
Household Products,Procter & Gamble,32,2015,Household and Personal Products,OH,Cincinnati,221280.0,84537.0,11643.0,144266.0,118000.0,no,no,no,yes
Industrials,Caterpillar,54,2015,Construction and Farm Machinery,IL,Peoria,48512.0,55184.0,3695.0,84681.0,114233.0,no,no,no,yes
Materials,International Paper,114,2015,"Packaging, Containers",TN,Memphis,23464.0,26221.0,555.0,28684.0,58000.0,no,no,no,yes
Media,Walt Disney,57,2015,Entertainment,CA,Burbank,178267.0,48813.0,7501.0,84186.0,180000.0,no,no,no,yes
Motor Vehicles & Parts,General Motors,6,2015,Motor Vehicles & Parts,MI,Detroit,60389.0,155929.0,3949.0,177677.0,216000.0,no,yes,no,yes
Retailing,Walmart,1,2015,General Merchandisers,AR,Bentonville,265344.0,485651.0,16363.0,203706.0,2200000.0,no,no,no,yes
Technology,Apple,5,2015,"Computers, Office Equipment",CA,Cupertino,724773.0,182795.0,39510.0,231839.0,97200.0,no,no,no,yes
Telecommunications,AT&T,12,2015,Telecommunications,TX,Dallas,169459.0,132447.0,6224.0,292829.0,243620.0,no,no,no,yes
Transportation,UPS,47,2015,"Mail, Package, and Freight Delivery",GA,Atlanta,87492.0,58232.0,3032.0,35471.0,336150.0,no,no,no,yes
Wholesalers,McKesson,11,2015,Wholesalers: Health Care,CA,San Francisco,52669.0,138030.0,1263.0,51759.0,42800.0,no,no,no,yes

In [16]:
a.size()

sector
Aerospace & Defense               96
Apparel                           47
Business Services                169
Chemicals                        125
Energy                           547
Engineering & Construction       112
Financials                       777
Food & Drug Stores                55
Food, Beverages & Tobacco        223
Health Care                      368
Hotels, Restaurants & Leisure     89
Household Products               103
Industrials                      155
Materials                        177
Media                             93
Motor Vehicles & Parts           100
Retailing                        422
Technology                       393
Telecommunications                81
Transportation                   158
Wholesalers                      210
dtype: int64

In [17]:
q=df['name'].unique()
q.shape

(2255,)

In [18]:
df['name'].value_counts()

name
U.S. Bancorp               28
Edison International       28
Johnson & Johnson          28
Abbott Laboratories        28
Owens Corning              26
                           ..
Par Pacific Holdings        1
RPM International           1
Select Medical Holdings     1
MDU Resources Group         1
Electronic Arts             1
Name: count, Length: 2255, dtype: int64

In [19]:
df.isnull().sum()

name                          0
rank                          0
year                          0
industry                      0
sector                     9440
headquarters_state            0
headquarters_city          6445
market_value_mil           8755
revenue_mil                   0
profit_mil                 8443
asset_mil                  8440
employees                  9440
founder_is_ceo             9440
female_ceo                 9440
newcomer_to_fortune_500    9440
global_500                 9940
dtype: int64

In [20]:
df.shape

(13940, 16)

In [21]:
len(df)

13940